---

- name: start nginx
  become: yes
  service:
    name: nginx
    state: started

- name: copy upstreams
  become: yes
  copy:
    src: upstreams
    dest: /etc/nginx/upstreams/quackup.upstreams
  notify:
    - restart nginx

- name: copy the locations
  become: yes
  copy:
    src: locations
    dest: /etc/nginx/locations/quackup.locations
  notify:
    - restart nginx

...
