---

- name: Copy Makefile
  copy:
    src: Makefile
    dest: "{{ ansible_env.HOME }}"

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: "{{ ansible_env.HOME }}"

- name: Copy proxy nginx.conf
  copy:
    src: nginx.conf
    dest: "{{ ansible_env.HOME }}"

- name: Update docker swarm deployment
  become: yes
  run_once: true
  shell: "make up"

...
