---
- hosts: quackup

  tasks:

    - name: copy Makefile
      copy:
        src: Makefile
        dest: ~/quackup

    - name: copy docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: ~/quackup

    - name: update swarm
      shell: "cd quackup && make up && cd .."
      become: yes
      
...
