---

- name: Ensure docker deamon is running
  become: true
  service:
    name: docker
    state: started

- name: Copy docker configuration
  become: true
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  register: config

- name: Restart docker
  when: config.changed
  become: true
  service:
    name: docker
    state: restarted

...
