---

- name: start nginx
  become: yes
  service:
    name: nginx
    state: started

- name: copy the locations
  become: yes
  copy:
    src: locations
    dest: /etc/nginx/sites-available/quackup.locations
  register: locations

- name: restart nginx
  when: locations.changed
  become: yes
  service:
    name: nginx
    state: restarted

...
